[workspace]
members = [
    "crates/ffxiv_items",
    "crates/ffxiv_server",
    "crates/ffxiv_universalis",
    "crates/mock_traits",
]
resolver = "2"

[profile.release-debug]
inherits = "release"
debug = true

[profile.docker]
inherits = "release"
incremental = true
lto = "thin"
