services:
  ffxiv-server:
    build:
      dockerfile_inline: |
        FROM rust:1.72.1
        RUN apt-get update && apt-get install -y lld && rm -rf /var/lib/apt/lists/*
    working_dir: /crates
    command: [ "./startup.sh" ]
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3001/v1/health"]
      interval: 10s
      timeout: 10s
      retries: 120
      start_period: 10s
    environment:
      - RUSTFLAGS=-C link-arg=-fuse-ld=lld
      - CARGO_INCREMENTAL=true
      - FFXIV_ITEM_DB_CONN=mysql://user:password@ffxiv-items-db:3306/ffxiv_items
    depends_on:
      ffxiv-items-db:
        condition: service_healthy
    volumes:
      - ./crates:/crates

  ffxiv-items-db:
    image: mysql:8.0
    ports: ["3306:3306"]
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "ffxiv_items"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    # command: ["--general_log=1", "--general_log_file=/opt/mysql_logs/mysql.log"]
    # volumes:
    #   - ./crates/_artifacts:/opt/mysql_logs

  nextjs-server:
    image: node:20
    working_dir: /nextjs
    command: [ "./startup.sh" ]
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/v1/health"]
      interval: 10s
      timeout: 10s
      retries: 120
      start_period: 10s
    volumes:
      - ./frontend:/nextjs
      - /nextjs/node_modules/
      - /nextjs/.next/
      - /nextjs/.pnpm-store/

  nginx:
    image: nginx:latest
    ports: [ "80:80" ]
    command: [ "nginx", "-g", "daemon off;" ]
    depends_on:
      ffxiv-server:
        condition: service_healthy
      nextjs-server:
        condition: service_healthy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/etc/nginx/logs
