services:
  ffxiv-server:
    image: rust:1.72
    working_dir: /ffxiv_server
    command: [ "cargo", "run", "--profile", "docker" ]
    ports: [ "3001:3001" ]
    volumes:
      - ./ffxiv_server:/ffxiv_server
      - ./ffxiv_items:/ffxiv_items
      - ./ffxiv_universalis:/ffxiv_universalis

  http-server:
    image: httpd:2.4
    ports: [ "8080:80" ]
    depends_on:
      typescript-watch:
        condition: service_started
    volumes:
      - ./frontend:/usr/local/apache2/htdocs/

  typescript-watch:
    image: mcr.microsoft.com/devcontainers/typescript-node:20
    working_dir: /frontend-ts
    command: [ "tsc", "--watch" ]
    depends_on:
      typescript-init:
        condition: service_completed_successfully
    volumes:
      - ./frontend-ts:/frontend-ts
      - ./frontend:/frontend

  typescript-init:
    image: mcr.microsoft.com/devcontainers/typescript-node:20
    working_dir: /frontend-ts
    command: [ "npm", "install" ]
    volumes:
      - ./frontend-ts:/frontend-ts
