services:
  ffxiv-server:
    image: rust:1.72
    working_dir: /crates
    command: [ "./startup.sh" ]
    ports: [ "3001:3001" ]
    environment:
      - FFXIV_DATA_CENTERS=Dynamis
    volumes:
      - ./crates:/crates

  http-server:
    image: httpd:2.4
    ports: [ "8080:80" ]
    depends_on:
      typescript-watch:
        condition: service_started
        required: false
    volumes:
      - ./frontend/src-js:/usr/local/apache2/htdocs/

  typescript-watch:
    image: mcr.microsoft.com/devcontainers/typescript-node:20
    working_dir: /src-ts
    command: [ "tsc", "--watch" ]
    depends_on:
      typescript-init:
        condition: service_completed_successfully
    profiles: [ watch ]
    volumes:
      - ./frontend/src-ts:/src-ts
      - ./frontend/src-js:/src-js

  typescript-init:
    image: mcr.microsoft.com/devcontainers/typescript-node:20
    working_dir: /src-ts
    command: [ "sh", "startup.sh" ]
    volumes:
      - ./frontend/src-ts:/src-ts
      - ./frontend/src-js:/src-js
