export type ValidExchangeType = 'purpleScrips' | 'whiteScrips' | 'skybuildersScrips';

export interface ExchangeCost {
    type: ValidExchangeType,
    name: string,
    search: string,
    count: number,
}

export const exchangeCosts: ExchangeCost[] = [
    { type: 'purpleScrips', name: "Purple Crafting Scrips", count: 20, search: ":name ^Rarefied, :rlevel 90" },
    { type: 'whiteScrips', name: "White Crafting Scrips", count: 20, search: ":name ^Rarefied, :rlevel 50|89" },
    { type: 'skybuildersScrips', name: "Skybuilders' Scrips", count: 50, search: ":name ^Grade 4 Skybuilders', :rlevel 80" },
];

type Currency = { type: 'purpleScrips' } | { type: 'whiteScrips' } | { type: 'skybuildersScrips' };
export type ExchangeProfits = Currency & { scrips: number, name: string }

export const exchangeProfits: ExchangeProfits[] = [

    { type: 'purpleScrips', scrips: 125, name: 'Immutable Solution' },
    { type: 'purpleScrips', scrips: 500, name: "Craftsman's Competence Materia X" },
    { type: 'purpleScrips', scrips: 500, name: "Craftsman's Cunning Materia X" },
    { type: 'purpleScrips', scrips: 500, name: "Craftsman's Command Materia X" },
    { type: 'purpleScrips', scrips: 300, name: "Earthbreak Aethersand" },
    { type: 'purpleScrips', scrips: 800, name: "Hanging Lure Display" },

    { type: 'whiteScrips', scrips: 250, name: "Craftsman's Competence Materia IX" },
    { type: 'whiteScrips', scrips: 250, name: "Craftsman's Cunning Materia IX" },
    { type: 'whiteScrips', scrips: 250, name: "Craftsman's Command Materia IX" },
    { type: 'whiteScrips', scrips: 200, name: "Craftsman's Competence Materia VII" },
    { type: 'whiteScrips', scrips: 200, name: "Craftsman's Cunning Materia VII" },
    { type: 'whiteScrips', scrips: 200, name: "Craftsman's Command Materia VII" },
    { type: 'whiteScrips', scrips: 25, name: "Craftsman's Competence Materia IV" },
    { type: 'whiteScrips', scrips: 25, name: "Craftsman's Cunning Materia IV" },
    { type: 'whiteScrips', scrips: 25, name: "Craftsman's Command Materia IV" },
    { type: 'whiteScrips', scrips: 10, name: "Dusklight Aethersand" },
    { type: 'whiteScrips', scrips: 10, name: "Dawnlight Aethersand" },
    { type: 'whiteScrips', scrips: 20, name: "Everbright Aethersand" },
    { type: 'whiteScrips', scrips: 20, name: "Everborn Aethersand" },
    { type: 'whiteScrips', scrips: 20, name: "Everdeep Aethersand" },
    { type: 'whiteScrips', scrips: 10, name: "Chiaroglow Aethersand" },
    { type: 'whiteScrips', scrips: 10, name: "Scuroglow Aethersand" },
    { type: 'whiteScrips', scrips: 20, name: "Agedeep Aethersand" },
    { type: 'whiteScrips', scrips: 20, name: "Agewood Aethersand" },
    { type: 'whiteScrips', scrips: 20, name: "Ageflow Aethersand" },
    { type: 'whiteScrips', scrips: 30, name: "Levinstrike Aethersand" },
    { type: 'whiteScrips', scrips: 50, name: "Sky Spoon Lure" },
    { type: 'whiteScrips', scrips: 50, name: "Panic Jig" },

    { type: 'skybuildersScrips', scrips: 200, name: 'Skysteel Ingot' },
    { type: 'skybuildersScrips', scrips: 200, name: 'Skysteel Cloth' },
    { type: 'skybuildersScrips', scrips: 200, name: 'Skysteel Leather' },
    { type: 'skybuildersScrips', scrips: 100, name: "Ruby Red Dye" },
    { type: 'skybuildersScrips', scrips: 100, name: "Cherry Pink Dye" },
    { type: 'skybuildersScrips', scrips: 100, name: "Canary Yellow Dye" },
    { type: 'skybuildersScrips', scrips: 100, name: "Vanilla Yellow Dye" },
    { type: 'skybuildersScrips', scrips: 100, name: "Dragoon Blue Dye" },
    { type: 'skybuildersScrips', scrips: 100, name: "Turquoise Blue Dye" },
    { type: 'skybuildersScrips', scrips: 500, name: "Gunmetal Black Dye" },
    { type: 'skybuildersScrips', scrips: 500, name: "Pearl White Dye" },
    { type: 'skybuildersScrips', scrips: 500, name: "Metallic Brass Dye" },
    { type: 'skybuildersScrips', scrips: 8400, name: "Albino Karakul Horn" },
    { type: 'skybuildersScrips', scrips: 8400, name: "Ufiti Horn" },
    { type: 'skybuildersScrips', scrips: 8400, name: "Megalotragus Horn" },
    { type: 'skybuildersScrips', scrips: 8400, name: "Big Shell Whistle" },
    { type: 'skybuildersScrips', scrips: 8400, name: "Antelope Doe Horn" },
    { type: 'skybuildersScrips', scrips: 1800, name: "Ballroom Etiquette - The Winsome Wallflower" },
    { type: 'skybuildersScrips', scrips: 1800, name: "Ballroom Etiquette - Intelligent Impressions" },
    { type: 'skybuildersScrips', scrips: 1800, name: "Ballroom Etiquette - Emphatic Elucidation" },
    { type: 'skybuildersScrips', scrips: 1800, name: "Ballroom Etiquette - Uncouth Congratulations" },
    { type: 'skybuildersScrips', scrips: 1800, name: "Ballroom Etiquette - Next, Godliness" },
    { type: 'skybuildersScrips', scrips: 1800, name: "Ballroom Etiquette - Concealing Meals" },
    { type: 'skybuildersScrips', scrips: 900, name: "Ballroom Etiquette - Well Bread" },
    { type: 'skybuildersScrips', scrips: 1800, name: "Modern Aesthetics - Modern Legend" },
    { type: 'skybuildersScrips', scrips: 1800, name: "Modern Aesthetics - Controlled Chaos" },
    { type: 'skybuildersScrips', scrips: 1800, name: "Modern Aesthetics - Saintly Style" },
    { type: 'skybuildersScrips', scrips: 1200, name: "Miniature White Knight" },
    { type: 'skybuildersScrips', scrips: 1200, name: "Cerberpup" },
    { type: 'skybuildersScrips', scrips: 800, name: "Paissa Brat" },
    { type: 'skybuildersScrips', scrips: 800, name: "Hunting Hawk" },
    { type: 'skybuildersScrips', scrips: 800, name: "Baby Brachiosaur" },
    { type: 'skybuildersScrips', scrips: 800, name: "Pegasus Colt" },
    { type: 'skybuildersScrips', scrips: 1200, name: "Machinist Barding" },
    { type: 'skybuildersScrips', scrips: 1200, name: "Safety in Numbers Orchestrion Roll" },
    { type: 'skybuildersScrips', scrips: 1200, name: "The Mendicant's Relish Orchestrion Roll" },
    { type: 'skybuildersScrips', scrips: 1200, name: "The Heavens' Ward Orchestrion Roll" },
    { type: 'skybuildersScrips', scrips: 1200, name: "Hearthward Orchestrion Roll" },
    { type: 'skybuildersScrips', scrips: 1200, name: "What Is Love? Orchestrion Roll" },
    { type: 'skybuildersScrips', scrips: 1200, name: "Skyrise Orchestrion Roll" },
    { type: 'skybuildersScrips', scrips: 600, name: "Jewel Orchestrion Roll" },
    { type: 'skybuildersScrips', scrips: 600, name: "Paradise Found Orchestrion Roll" },
    { type: 'skybuildersScrips', scrips: 600, name: "Fealty Orchestrion Roll" },
    { type: 'skybuildersScrips', scrips: 600, name: "Stone and Steel Orchestrion Roll" },
    { type: 'skybuildersScrips', scrips: 600, name: "Order Yet Undeciphered Orchestrion Roll" },
    { type: 'skybuildersScrips', scrips: 600, name: "Freefall Orchestrion Roll" },
    { type: 'skybuildersScrips', scrips: 1800, name: "Parasol" },
    { type: 'skybuildersScrips', scrips: 1800, name: "Cheerful Checkered Parasol" },
    { type: 'skybuildersScrips', scrips: 1800, name: "Pastoral Dot Parasol" },
    { type: 'skybuildersScrips', scrips: 900, name: "Sky Blue Parasol" },
    { type: 'skybuildersScrips', scrips: 900, name: "Calming Checkered Parasol" },
    { type: 'skybuildersScrips', scrips: 2200, name: "Craftsman's Coverall Top" },
    { type: 'skybuildersScrips', scrips: 2200, name: "Craftsman's Singlet" },
    { type: 'skybuildersScrips', scrips: 2200, name: "Craftsman's Apron" },
    { type: 'skybuildersScrips', scrips: 2000, name: "Craftsman's Coverall Bottoms" },
    { type: 'skybuildersScrips', scrips: 2000, name: "Craftsman's Leather Trousers" },
    { type: 'skybuildersScrips', scrips: 1200, name: "Craftsman's Leather Shoes" },
    { type: 'skybuildersScrips', scrips: 1200, name: "Skyworker's Helmet" },
    { type: 'skybuildersScrips', scrips: 2200, name: "Skyworker's Singlet" },
    { type: 'skybuildersScrips', scrips: 1200, name: "Skyworker's Gloves" },
    { type: 'skybuildersScrips', scrips: 2200, name: "Skyworker's Bottoms" },
    { type: 'skybuildersScrips', scrips: 1200, name: "Skyworker's Boots" },
    { type: 'skybuildersScrips', scrips: 300, name: "Craftsman's Competence Materia VIII" },
    { type: 'skybuildersScrips', scrips: 240, name: "Craftsman's Competence Materia VII" },
    { type: 'skybuildersScrips', scrips: 300, name: "Craftsman's Cunning Materia VIII" },
    { type: 'skybuildersScrips', scrips: 240, name: "Craftsman's Cunning Materia VII" },
    { type: 'skybuildersScrips', scrips: 300, name: "Craftsman's Command Materia VIII" },
    { type: 'skybuildersScrips', scrips: 240, name: "Craftsman's Command Materia VII" },
    { type: 'skybuildersScrips', scrips: 300, name: "Gatherer's Guerdon Materia VIII" },
    { type: 'skybuildersScrips', scrips: 240, name: "Gatherer's Guerdon Materia VII" },
    { type: 'skybuildersScrips', scrips: 300, name: "Gatherer's Guile Materia VIII" },
    { type: 'skybuildersScrips', scrips: 240, name: "Gatherer's Guile Materia VII" },
    { type: 'skybuildersScrips', scrips: 300, name: "Gatherer's Grasp Materia VIII" },
    { type: 'skybuildersScrips', scrips: 240, name: "Gatherer's Grasp Materia VII" },

];

export const scripsPerCraft: Record<ValidExchangeType, (_: number) => number> = {
    'purpleScrips': (_: number) => 144,
    'skybuildersScrips': (_: number) => 63,
    'whiteScrips': (level: number) => whiteScripsPerCraft[level],
}

const whiteScripsPerCraft: Record<number, number> = {
    89: 198,
    87: 171,
    85: 157,
    83: 142,
    81: 128,
    80: 114,
    78: 99,
    76: 85,
    74: 82,
    72: 68,
    70: 54,
    68: 54,
    66: 54,
    64: 54,
    62: 54,
    60: 54,
    58: 54,
    56: 54,
    54: 54,
    52: 54,
    50: 54,
}
