export type ValidExchangeType = 'purpleScrips' | 'whiteScrips' | 'tickets';

export interface ExchangeCost {
    type: ValidExchangeType,
    name: string,
    search: string,
    count: number,
    exchange: number,
}

export const exchangeCosts: ExchangeCost[] = [
    { type: 'purpleScrips', name: "Purple Crafting Scrips", count: 20, search: ":name ^Rarefied, :rlevel 90", exchange: 20 * 144 },
    { type: 'whiteScrips', name: "White Crafting Scrips", count: 20, search: ":name ^Rarefied, :rlevel 61|69", exchange: 20 * 54 },
    { type: 'tickets', name: "Skybuilders' Scrips", count: 50, search: ":name ^Grade 4 Skybuilders', :rlevel 80", exchange: 50 * 63 },
];

type Currency = { purpleScrips: number } | { whiteScrips: number } | { tickets: number };
export type ExchangeProfits = Currency & { name: string }

export const exchangeProfits: ExchangeProfits[] = [
    { purpleScrips: 125, name: 'Immutable Solution' },
    { purpleScrips: 500, name: "Craftsman's Competence Materia X" },
    { purpleScrips: 500, name: "Craftsman's Cunning Materia X" },
    { purpleScrips: 500, name: "Craftsman's Command Materia X" },

    { whiteScrips: 250, name: "Craftsman's Competence Materia IX" },
    { whiteScrips: 250, name: "Craftsman's Cunning Materia IX" },
    { whiteScrips: 250, name: "Craftsman's Command Materia IX" },
    { whiteScrips: 200, name: "Craftsman's Competence Materia VII" },
    { whiteScrips: 200, name: "Craftsman's Cunning Materia VII" },
    { whiteScrips: 200, name: "Craftsman's Command Materia VII" },
    { whiteScrips: 25, name: "Craftsman's Competence Materia IV" },
    { whiteScrips: 25, name: "Craftsman's Cunning Materia IV" },
    { whiteScrips: 25, name: "Craftsman's Command Materia IV" },

    { tickets: 200, name: 'Skysteel Ingot' },
    { tickets: 200, name: 'Skysteel Cloth' },
    { tickets: 200, name: 'Skysteel Leather' },
    { tickets: 240, name: "Gatherer's Guerdon Materia VII" },
    { tickets: 300, name: "Gatherer's Guerdon Materia VIII" },
    { tickets: 100, name: "Ruby Red Dye" },
    { tickets: 100, name: "Cherry Pink Dye" },
    { tickets: 100, name: "Canary Yellow Dye" },
    { tickets: 100, name: "Vanilla Yellow Dye" },
    { tickets: 100, name: "Dragoon Blue Dye" },
    { tickets: 100, name: "Turquoise Blue Dye" },
    { tickets: 500, name: "Gunmetal Black Dye" },
    { tickets: 500, name: "Pearl White Dye" },
    { tickets: 500, name: "Metallic Brass Dye" },
    { tickets: 8400, name: "Albino Karakul Horn" },
    { tickets: 8400, name: "Ufiti Horn" },
    { tickets: 8400, name: "Megalotragus Horn" },
    { tickets: 8400, name: "Big Shell Whistle" },
    { tickets: 8400, name: "Antelope Doe Horn" },
    { tickets: 1800, name: "Ballroom Etiquette - The Winsome Wallflower" },
    { tickets: 1800, name: "Ballroom Etiquette - Intelligent Impressions" },
    { tickets: 1800, name: "Ballroom Etiquette - Emphatic Elucidation" },
    { tickets: 1800, name: "Ballroom Etiquette - Uncouth Congratulations" },
    { tickets: 1800, name: "Ballroom Etiquette - Next, Godliness" },
    { tickets: 1800, name: "Ballroom Etiquette - Concealing Meals" },
    { tickets: 900, name: "Ballroom Etiquette - Well Bread" },
    { tickets: 1800, name: "Modern Aesthetics - Modern Legend" },
    { tickets: 1800, name: "Modern Aesthetics - Controlled Chaos" },
    { tickets: 1800, name: "Modern Aesthetics - Saintly Style" },
    { tickets: 1200, name: "Miniature White Knight" },
    { tickets: 1200, name: "Cerberpup" },
    { tickets: 800, name: "Paissa Brat" },
    { tickets: 800, name: "Hunting Hawk" },
    { tickets: 800, name: "Baby Brachiosaur" },
    { tickets: 800, name: "Pegasus Colt" },
    { tickets: 1200, name: "Machinist Barding" },
    { tickets: 1200, name: "Safety in Numbers Orchestrion Roll" },
    { tickets: 1200, name: "The Mendicant's Relish Orchestrion Roll" },
    { tickets: 1200, name: "The Heavens' Ward Orchestrion Roll" },
    { tickets: 1200, name: "Hearthward Orchestrion Roll" },
    { tickets: 1200, name: "What Is Love? Orchestrion Roll" },
    { tickets: 1200, name: "Skyrise Orchestrion Roll" },
    { tickets: 600, name: "Jewel Orchestrion Roll" },
    { tickets: 600, name: "Paradise Found Orchestrion Roll" },
    { tickets: 600, name: "Fealty Orchestrion Roll" },
    { tickets: 600, name: "Stone and Steel Orchestrion Roll" },
    { tickets: 600, name: "Order Yet Undeciphered Orchestrion Roll" },
    { tickets: 600, name: "Freefall Orchestrion Roll" },
    { tickets: 1800, name: "Parasol" },
    { tickets: 1800, name: "Cheerful Checkered Parasol" },
    { tickets: 1800, name: "Pastoral Dot Parasol" },
    { tickets: 900, name: "Sky Blue Parasol" },
    { tickets: 900, name: "Calming Checkered Parasol" },
    { tickets: 2200, name: "Craftsman's Coverall Top" },
    { tickets: 2200, name: "Craftsman's Singlet" },
    { tickets: 2200, name: "Craftsman's Apron" },
    { tickets: 2000, name: "Craftsman's Coverall Bottoms" },
    { tickets: 2000, name: "Craftsman's Leather Trousers" },
    { tickets: 1200, name: "Craftsman's Leather Shoes" },
    { tickets: 1200, name: "Skyworker's Helmet" },
    { tickets: 2200, name: "Skyworker's Singlet" },
    { tickets: 1200, name: "Skyworker's Gloves" },
    { tickets: 2200, name: "Skyworker's Bottoms" },
    { tickets: 1200, name: "Skyworker's Boots" },
];
